/**
 * Centralized dictionary of all UI text strings, labels, placeholders, and error messages.
 */
export const STRINGS = {
  APP: {
    TITLE: "TaskFlow",
    SUBTITLE: "Hexagonal Architecture Management Console",
    NAV_USERS: "Users",
    NAV_TASKS: "Tasks",
    NAV_NOTIFICATIONS: "Notifications",
    FOOTER_TEXT: "TaskFlow Hexagonal Architecture Full-Stack System",
  },
  COMMON: {
    LOADING: "Loading...",
    SUBMITTING: "Submitting...",
    SUBMIT: "Submit",
    CANCEL: "Cancel",
    REFRESH: "Refresh",
    SEARCH: "Search",
    ACTIONS: "Actions",
    CREATED_AT: "Created At",
    UPDATED_AT: "Updated At",
    ID: "ID",
    STATUS: "Status",
    UNASSIGNED: "Unassigned",
    NOT_AVAILABLE: "N/A",
    VIEW: "View",
    CLOSE: "Close",
    CLEAR: "Clear",
    ALL: "All",
  },
  USERS: {
    SECTION_TITLE: "User Management",
    REGISTER_TITLE: "Register New User",
    REGISTER_NAME_LABEL: "Full Name",
    REGISTER_NAME_PLACEHOLDER: "Enter full name (e.g. Alice Smith)",
    REGISTER_EMAIL_LABEL: "Email Address",
    REGISTER_EMAIL_PLACEHOLDER: "Enter email address (e.g. alice@example.com)",
    REGISTER_SUBMIT_BUTTON: "Register User",
    REGISTER_SUCCESS: "User registered successfully!",
    LIST_TITLE: "Registered Users",
    LIST_EMPTY: "No users registered yet.",
    LOOKUP_TITLE: "View User By ID",
    LOOKUP_ID_LABEL: "User ID",
    LOOKUP_ID_PLACEHOLDER: "Enter user UUID",
    LOOKUP_BUTTON: "Lookup User",
    DETAIL_TITLE: "User Details",
    DETAIL_NAME: "Name",
    DETAIL_EMAIL: "Email",
    DETAIL_ID: "User ID",
    DETAIL_CREATED: "Registered",
    VIEW_NOTIFICATIONS_BUTTON: "View Notifications",
    VIEW_USER_BUTTON: "View Details",
    SELECT_USER_PROMPT: "Select a user...",
  },
  TASKS: {
    SECTION_TITLE: "Task Management",
    CREATE_TITLE: "Create New Task",
    CREATE_TITLE_LABEL: "Task Title",
    CREATE_TITLE_PLACEHOLDER: "Enter task title (e.g. Fix login bug)",
    CREATE_DESC_LABEL: "Description",
    CREATE_DESC_PLACEHOLDER: "Enter task description (optional)",
    CREATE_ASSIGNEE_LABEL: "Assignee (Optional)",
    CREATE_SUBMIT_BUTTON: "Create Task",
    CREATE_SUCCESS: "Task created successfully!",
    LIST_TITLE: "All Tasks",
    LIST_EMPTY: "No tasks created yet.",
    LOOKUP_TITLE: "View Task By ID",
    LOOKUP_ID_LABEL: "Task ID",
    LOOKUP_ID_PLACEHOLDER: "Enter task UUID",
    LOOKUP_BUTTON: "Lookup Task",
    DETAIL_TITLE: "Task Details",
    DETAIL_TITLE_LABEL: "Title",
    DETAIL_DESC_LABEL: "Description",
    DETAIL_STATUS_LABEL: "Status",
    DETAIL_ASSIGNEE_TITLE: "Assignee Details",
    DETAIL_NO_ASSIGNEE: "This task is currently unassigned.",
    ASSIGN_TITLE: "Assign Task to User",
    ASSIGN_TASK_SELECT_LABEL: "Select Task",
    ASSIGN_USER_SELECT_LABEL: "Select Assignee",
    ASSIGN_SUBMIT_BUTTON: "Assign Task",
    ASSIGN_SUCCESS: "Task successfully assigned!",
    VIEW_TASK_BUTTON: "View Details",
    QUICK_ASSIGN_BUTTON: "Assign",
  },
  NOTIFICATIONS: {
    SECTION_TITLE: "User Notifications",
    SELECT_USER_LABEL: "Select User to View Notifications",
    SELECT_USER_PLACEHOLDER: "Choose a user to view their notifications",
    MANUAL_USER_ID_LABEL: "Or Enter User ID",
    MANUAL_USER_ID_PLACEHOLDER: "Enter user UUID directly",
    LOAD_BUTTON: "Load Notifications",
    LIST_TITLE: "Notifications",
    LIST_EMPTY: "No notifications found for this user.",
    SELECT_PROMPT: "Please select a user to inspect their notification feed.",
    STATUS_READ: "Read",
    STATUS_UNREAD: "Unread",
    MARK_AS_READ_BUTTON: "Mark as Read",
    MARK_AS_READ_SUCCESS: "Notification marked as read.",
    NOTIFICATION_FOR_USER: "Notifications for User",
  },
  ERRORS: {
    NETWORK_ERROR: "Unable to connect to the server. Please check your network or server status.",
    UNKNOWN_ERROR: "An unexpected error occurred.",
    USER_NAME_REQUIRED: "Name is required.",
    USER_EMAIL_REQUIRED: "Valid email is required.",
    TASK_TITLE_REQUIRED: "Task title is required.",
    TASK_ID_REQUIRED: "Task ID is required.",
    USER_ID_REQUIRED: "User ID is required.",
    ASSIGNEE_REQUIRED: "Please select an assignee user.",
    TASK_NOT_FOUND: "Task not found.",
    USER_NOT_FOUND: "User not found.",
    NOTIFICATION_NOT_FOUND: "Notification not found.",
  },
} as const;
